-- Salin dan jalankan (Run) kode SQL ini di bagian SQL Editor pada dashboard Supabase Anda.

CREATE TABLE IF NOT EXISTS potholes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    speed REAL DEFAULT 0,
    diameter REAL DEFAULT 0,
    depth REAL DEFAULT 0,
    confidence REAL DEFAULT 0,
    severity TEXT NOT NULL,
    snapshot_path TEXT,
    google_maps_url TEXT
);

-- Mengaktifkan Row Level Security (RLS) namun diset agar bisa ditulis dan dibaca publik
-- (Hanya untuk keperluan testing, sebaiknya gunakan Authentication jika untuk Production)
ALTER TABLE potholes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
ON potholes FOR SELECT
USING (true);

CREATE POLICY "Allow public insert access"
ON potholes FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public delete access"
ON potholes FOR DELETE
USING (true);

-- Membuat Storage Bucket bernama 'snapshots' jika belum ada (Anda juga bisa membuatnya secara manual di menu Storage)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('snapshots', 'snapshots', true)
ON CONFLICT DO NOTHING;

CREATE POLICY "Give public access to snapshots bucket"
ON storage.objects FOR SELECT
USING (bucket_id = 'snapshots');

CREATE POLICY "Allow public to insert into snapshots bucket"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'snapshots');
